# Generated by Django 4.2.14 on 2025-05-29 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=30)),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Karate', 'Karate'), ('Wrestling', 'Wrestling'), ('BJJ', 'BJJ'), ('Judo', 'Judo'), ('Muay Thai/Kickboxing', 'Muay Thai/Kickboxing'), ('MMA', 'MMA'), ('Boxing', 'Boxing')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('website', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('monthlyPrice', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('coaches', models.ManyToManyField(to='api.coach')),
            ],
        ),
    ]
