# Generated by Django 4.2.14 on 2025-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='specialty',
            field=models.CharField(choices=[('Karate', 'Karate'), ('Wrestling', 'Wrestling'), ('BJJ', 'BJJ'), ('Judo', 'Judo'), ('Muay Thai/Kickboxing', 'Muay Thai/Kickboxing'), ('MMA', 'MMA'), ('Boxing', 'Boxing'), ('Fitness', 'Fitness')], max_length=30),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('Karate', 'Karate'), ('Wrestling', 'Wrestling'), ('BJJ', 'BJJ'), ('Judo', 'Judo'), ('Muay Thai/Kickboxing', 'Muay Thai/Kickboxing'), ('MMA', 'MMA'), ('Boxing', 'Boxing'), ('Fitness', 'Fitness')], max_length=20),
        ),
    ]
